services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - devsecops-net
    depends_on:
      - postgres

  frontend:
    image: node:18-slim
    container_name: frontend
    working_dir: /app
    command: sh -c "cd frontend && npm install && npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - devsecops-net
    depends_on:
      - backend

volumes:
  frontend_node_modules:

networks:
  devsecops-net:
    external: true